# image: rustdocker/rust:nightly

# before_script:
#   - apt-get update
#   - apt-get -y install sudo curl git file g++ cmake
#   - echo Installing Rust from $CI_BUILD_NAME channel
#   - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $CI_BUILD_NAME
#   - . ~/.cargo/env && rustc -V && cargo -V

stages:
  - test
  - deploy

stable:
  image: rustdocker/rust:stable
  stage: test
  script:
    - cargo test --verbose --jobs 1 --release

beta:
  image: rustdocker/rust:beta
  stage: test
  script:
    - cargo test --verbose --jobs 1 --release

nightly:
  image: rustdocker/rust:nightly
  stage: test
  script:
    - cargo test --verbose --jobs 1 --release

pages:
  image: rustdocker/rust:stable
  stage: deploy
  only:
    - master
  script:
    - cargo doc
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
    - public
