image: ubuntu:xenial

before_script:
  - apt-get update
  - apt-get -y install sudo curl git file g++ cmake
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly

stages:
  - test
  - deploy

stable:
  stage: test
  script:
    - rustup install stable
    - cargo test --verbose

beta:
  stage: test
  script:
    - rustup install beta
    - cargo test --verbose

nightly:
  stage: test
  script:
    - rustup install nightly
    - cargo test --verbose

pages:
  stage: deploy
  only:
    - doc
  script:
    - cargo doc
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
    - public
