image: ubuntu:xenial

before_script:
  - apt-get update
  - apt-get -y install sudo curl git file g++ cmake

stages:
  - test
  - deploy

stable:
  stage: test
  script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
    - . ~/.cargo/env && cargo test --verbose

beta:
  stage: test
  script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain beta
    - . ~/.cargo/env && cargo test --verbose

nightly:
  stage: test
  script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
    - . ~/.cargo/env && cargo test --verbose

pages:
  stage: deploy
  only:
    - master
  script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
    - . ~/.cargo/env && cargo doc
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
    - public
