[package]
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
description = "Helps pipe your output through an external pager"
documentation = "https://docs.rs/pager"
homepage = "https://gitlab.com/imp/pager-rs"
keywords = ["pager", "less", "more"]
license = "Apache-2.0/MIT"
name = "pager"
readme = "README.md"
repository = "https://gitlab.com/imp/pager-rs.git"
version = "0.9.3"

[dependencies]
libc = "0.2"
